#spring:
#  h2:
#    console:
#      enabled: true
#  datasource:
#    platform: h2
#    url: jdbc:h2:mem:testdb  # Use an in-memory H2 database
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
#  allowed:
#    resources: /h2-console/**

welcome:
  message: Welcome to my app

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/dcbapp
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
