spring:
  h2:
    console:
      enabled: true
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb  # Use an in-memory H2 database
    username: sa
    password:
    driverClassName: org.h2.Driver
  allowed:
    resources: /h2-console/**